name: money_pro_taxi
description: Персональный финансовый трекер для работы в Яндекс.Такси и Такси Максим + функции Money Pro
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  shared_preferences: ^2.0.17
  sqflite: ^2.2.8
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

